### ISSUE TITLE
ZK-Compression-CLI BROKEN: light init programme does not create buildable project.

### ISSUE THREAD

**Issue by 0xNico** [Lightprotocol/light-protocol#1256]
When utilising the `zk-compression-cli` as shown in the example within the documents to initialise a project you will get package graph issues for custom light packages. Meaning it is impossible to init a light project with the cli. 

### Tested
+ Updating all anchor-lang versions to match 0.29.0 generated by cli. 
+ Update all anchor-lang versions to latest. 
+ Run cargo update to look for latest package patches 
+ Manually search for dependency issue and attempt to patch over, impossible. 

### Working method for compression project building. 
+ Start project from scratch with anchor init 
+ Add dependencies not based on the patch graph 
+ Use solana version 1.18.22 force patch 
+ Manually integrate light dependencies into base empty project. 

<img width="1144" alt="Screenshot 2024-09-25 at 11 11 25" src="https://github.com/user-attachments/assets/1f43a989-88cb-453c-ac64-a7843127fe7a">

**Comment by 0xNico** [comment]
This is for sure caused by `blake3` please patch - it's impossible to build a light program right now in the current state. @SwenSchaeferjohann @ananas-block 

```
error: failed to run custom build command for `blake3 v1.5.1`

Caused by:
  process didn't exit successfully: `/Users/nico/Desktop/ReflectRMS/riskoracle/target/release/build/blake3-76b8ba49599c2a73/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=CARGO_FEATURE_PURE
  cargo:rerun-if-env-changed=CARGO_FEATURE_NO_NEON
  cargo:rerun-if-env-changed=CARGO_FEATURE_NEON
  cargo:rerun-if-env-changed=CARGO_FEATURE_NEON
  cargo:rerun-if-env-changed=CARGO_FEATURE_NO_NEON
  cargo:rerun-if-env-changed=CARGO_FEATURE_PURE
  cargo:rustc-cfg=blake3_neon
  OUT_DIR = Some(/Users/nico/Desktop/ReflectRMS/riskoracle/target/release/build/blake3-f834dd9a7b088b3c/out)
  TARGET = Some(aarch64-apple-darwin)
  OPT_LEVEL = Some(3)
  HOST = Some(aarch64-apple-darwin)
  cargo:rerun-if-env-changed=CC_aarch64-apple-darwin
  CC_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CC_aarch64_apple_darwin
  CC_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = Some(/Users/nico/.local/share/solana/install/releases/1.18.22/solana-release/bin/sdk/sbf/dependencies/platform-tools/llvm/bin/clang)
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(false)
  cargo:rerun-if-env-changed=MACOSX_DEPLOYMENT_TARGET
  MACOSX_DEPLOYMENT_TARGET = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64-apple-darwin
  CFLAGS_aarch64-apple-darwin = None
  cargo:rerun-if-env-changed=CFLAGS_aarch64_apple_darwin
  CFLAGS_aarch64_apple_darwin = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:warning=In file included from c/blake3_neon.c:1:
  cargo:warning=c/blake3_impl.h:4:10: fatal error: 'assert.h' file not found
  cargo:warning=    4 | #include <assert.h>
  cargo:warning=      |          ^~~~~~~~~~
  cargo:warning=1 error generated.

  --- stderr


  error occurred: Command env -u IPHONEOS_DEPLOYMENT_TARGET "/Users/nico/.local/share/solana/install/releases/1.18.22/solana-release/bin/sdk/sbf/dependencies/platform-tools/llvm/bin/clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=arm64-apple-darwin" "-mmacosx-version-min=14.4" "-Wall" "-Wextra" "-std=c11" "-o" "/Users/nico/Desktop/ReflectRMS/riskoracle/target/release/build/blake3-f834dd9a7b088b3c/out/db3b6bfb95261072-blake3_neon.o" "-c" "c/blake3_neon.c" with args clang did not execute successfully (status code exit status: 1).
```

**Comment by SwenSchaeferjohann** [comment]
thanks for raising this @0xNico 

for visibility, (1) the package graph issue is resolve using `light init` with cli >= `v.0.17.0 `

for existing projects, remove these two patches from the cargo.toml
-`"solana-cli-output" = { git = "https://github.com/lightprotocol/agave", branch = "v1.18.22-enforce-cpi-tracking" }`
-`"solana-rpc" = { git = "https://github.com/lightprotocol/agave", branch = "v1.18.22-enforce-cpi-tracking" }`

then remove cargo lock
then run `cargo clean`
then run `anchor build`
the run `cargo test-sbf`


independently, to fix the `error: 'assert.h' file not found` during build, ensure that on MacOS you:
`export CPATH="/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include:$CPATH"`
in your terminal session
